// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TRID.FeatureFiles
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CardsValidation", SourceFile="FeatureFiles\\CardsValidation.feature", SourceLine=0)]
    public partial class CardsValidationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CardsValidation.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CardsValidation", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage(string scenarioNo, string rowNumber, string pcSheetName, string miSheetName, string cdSheetName, string aRowNumber, string aSheetName, string eSheetName, string egSheetName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
                    "ge", exampleTags);
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
testRunner.Given("user is at TRID application homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.And(string.Format("user have closing disclosure data from excel sheet {0} for the scenario {1}", cdSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.And(string.Format("user have Mortgage Insurance data from excel sheet {0} for the scenario {1}", miSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And(string.Format("user have variable loan data from excel sheet {0} for the scenario {1}", aSheetName, aRowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And(string.Format("user have Prepaid Charges data from excel sheet {0} for the scenario {1}", pcSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And(string.Format("user have Export data from excel sheet {0} for the scenario {1}", eSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And(string.Format("user have Escrow Grid data from excel sheet {0} for the scenario {1}", egSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
testRunner.When("user navigate to Loan Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("user selects Calculation Method", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And("user selects loan type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And("user selects Frequency of Payments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And("user selects Loan Term", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And("user selects Repayment Term Type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
    testRunner.And("user enters Loan detail input values for computation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("user enters Escrow Grid Input values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("user enters all input values for Prepaid Charges", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And("user enters input value for prepaid custom fields", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("user navigates to MI Inputs and Results Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("user enters pmi rate values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("user enters other pmi input values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.And("user enters FHA/USDA Loan Details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("user enters disclosed input values for Mortgage Insurance", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("user navigates to Disclosure Inputs Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.And("user enters disclosed input values for Closing Disclosure Loan Terms & Projected " +
                    "Payments", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
 testRunner.And("user enters disclosed input values for Closing Disclosure Loan Calculations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("user enters disclosed input values for Property Cost and Escrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("user navigates to Loan Estimate Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("user enters disclsoed input values for Loan Estimate - Comparisons", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.And("user navigates to Export Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("user enters all input values for Export Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("user clicks on Export button to generate JSON file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
testRunner.Then("user navigates to Closing Disclosure Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
 testRunner.And("updated/computed Principal and Interest value should display on Closing Disclosur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("updated/computed Mortgage Insurance value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("updated/computed Estimated Total Monthly Payment value should display on Closing " +
                    "Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("updated/computed APR value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("APRWIN info value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("updated/computed Balloon Amount value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.And("updated/computed Total of Payments value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 43
 testRunner.And("updated/computed Finance Charge value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 44
 testRunner.And("updated/computed Amount Financed value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 45
 testRunner.And("updated/computed TIP value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("updated/computed Escrowed Prop Costs Over Year 1 from consummation date value sho" +
                    "uld display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.And("updated/computed Escrowed Property Costs Over Year 1 from date of 1st loan paymen" +
                    "t value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("updated/computed Initial Escrow Payment value should display on Closing Disclosur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("updated/computed Non Escrow Property Costs over one year value should display on " +
                    "Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("updated/computed Estimated Escrow value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("updated/computed Estimated Taxes, Insurance & Assessments value should display on" +
                    " Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("user navigates to MI Inputs and Results Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("updated/computed Scheduled PMI Termination Date value should display on Closing D" +
                    "isclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.And("updated/computed Cancel Date value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("updated/computed Upfront MIP values value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("user navigates to Loan Estimate Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("updated/computed in 5 Years value should display on Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("updated/computed in 5 Years principal value should display on Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 001", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_001()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("001", "2", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 002", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_002()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("002", "3", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 003", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_003()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("003", "4", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 004", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_004()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("004", "5", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 006", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_006()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("006", "6", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 007", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_007()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("007", "7", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 008", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_008()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("008", "8", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 009", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_009()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("009", "9", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 011", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_011()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("011", "10", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 012", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_012()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("012", "11", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 013", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_013()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("013", "12", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 014", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_014()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("014", "13", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 016", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_016()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("016", "14", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 017", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_017()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("017", "15", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 019", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_019()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("019", "16", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 020", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_020()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("020", "17", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 021", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_021()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("021", "18", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 022", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_022()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("022", "19", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 023", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_023()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("023", "20", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 024", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_024()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("024", "21", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 025", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_025()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("025", "22", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 026", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_026()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("026", "23", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 040", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_040()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("040", "25", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 041", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_041()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("041", "26", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 042", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_042()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("042", "27", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 043", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_043()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("043", "28", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 044", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_044()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("044", "29", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 045", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_045()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("045", "30", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 046", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_046()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("046", "31", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 047", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_047()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("047", "32", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 048", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_048()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("048", "33", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 050", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_050()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("050", "36", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 051", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_051()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("051", "37", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 052", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_052()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("052", "38", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 053", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_053()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("053", "39", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 054", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_054()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("054", "40", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 055", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_055()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("055", "41", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 056", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_056()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("056", "42", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 057", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_057()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("057", "43", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 070", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_070()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("070", "56", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 071", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_071()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("071", "57", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 072", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_072()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("072", "58", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 073", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_073()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("073", "59", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 074", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_074()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("074", "60", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 075", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_075()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("075", "61", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 076", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_076()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("076", "62", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 077", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_077()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("077", "63", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 090", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_090()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("090", "76", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 091", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_091()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("091", "77", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 092", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_092()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("092", "78", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 093", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_093()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("093", "79", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 094", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_094()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("094", "80", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 095", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_095()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("095", "81", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 096", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_096()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("096", "82", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 097", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_097()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("097", "83", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 110", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_110()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("110", "96", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 111", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_111()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("111", "97", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 112", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_112()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("112", "98", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 113", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_113()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("113", "99", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 114", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_114()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("114", "100", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 115", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_115()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("115", "101", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 116", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_116()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("116", "102", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 117", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_117()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("117", "103", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "1", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 138", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_138()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("138", "124", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "2", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 139", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_139()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("139", "125", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "3", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 140", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_140()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("140", "126", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "4", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 141", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_141()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("141", "127", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "5", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 142", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_142()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("142", "128", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "6", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 143", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_143()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("143", "129", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "7", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 144", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_144()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("144", "130", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "8", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 145", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_145()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("145", "131", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "9", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 146", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_146()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("146", "132", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "10", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 147", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_147()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("147", "133", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "11", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 150", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_150()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("150", "136", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "12", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Giving inputs from Excel file and validating cards value on Closing Disclosure pa" +
            "ge, 151", SourceLine=60)]
        public virtual void GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage_151()
        {
            this.GivingInputsFromExcelFileAndValidatingCardsValueOnClosingDisclosurePage("151", "137", "PrepaidCharges", "MortgageInsurance", "ClosingDisclosure", "13", "ARMTerms", "Export", "EscrowGrid", ((string[])(null)));
#line hidden
        }
        
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage(string scenarioNo, string rowNumber, string cdSheetName, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Uploading JSON file and Validating cards value on Closing Disclosure page", exampleTags);
#line 139
this.ScenarioSetup(scenarioInfo);
#line 140
testRunner.Given("user is at TRID application homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 141
 testRunner.And(string.Format("user have closing disclosure data from excel sheet {0} for the scenario {1}", cdSheetName, rowNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 142
testRunner.When("user upload json file for the scenario", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 143
testRunner.Then("user navigates to Closing Disclosure Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 144
 testRunner.And("updated/computed Principal and Interest value should display on Closing Disclosur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.And("updated/computed Mortgage Insurance value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 146
 testRunner.And("updated/computed Estimated Total Monthly Payment value should display on Closing " +
                    "Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
 testRunner.And("updated/computed APR value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.And("APRWIN info value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.And("updated/computed Balloon Amount value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 150
 testRunner.And("updated/computed Total of Payments value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.And("updated/computed Finance Charge value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.And("updated/computed Amount Financed value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 153
 testRunner.And("updated/computed TIP value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.And("updated/computed Escrowed Prop Costs Over Year 1 from consummation date value sho" +
                    "uld display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
 testRunner.And("updated/computed Escrowed Property Costs Over Year 1 from date of 1st loan paymen" +
                    "t value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
 testRunner.And("updated/computed Initial Escrow Payment value should display on Closing Disclosur" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 157
 testRunner.And("updated/computed Non Escrow Property Costs over one year value should display on " +
                    "Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 158
 testRunner.And("updated/computed Estimated Escrow value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("updated/computed Estimated Taxes, Insurance & Assessments value should display on" +
                    " Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("user navigates to MI Inputs and Results Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 161
 testRunner.And("updated/computed Scheduled PMI Termination Date value should display on Closing D" +
                    "isclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.And("updated/computed Cancel Date value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.And("updated/computed Upfront MIP values value should display on Closing Disclosure", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.And("user navigates to Loan Estimate Cards Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("updated/computed in 5 Years value should display on Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 166
 testRunner.And("updated/computed in 5 Years principal value should display on Loan Estimate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 001", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_001()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("001", "2", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 002", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_002()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("002", "3", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 003", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_003()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("003", "4", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 004", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_004()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("004", "5", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 006", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_006()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("006", "6", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 007", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_007()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("007", "7", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 008", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_008()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("008", "8", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 009", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_009()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("009", "9", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 011", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_011()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("011", "10", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 012", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_012()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("012", "11", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 013", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_013()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("013", "12", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 014", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_014()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("014", "13", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 016", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_016()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("016", "14", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 017", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_017()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("017", "15", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 019", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_019()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("019", "16", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 020", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_020()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("020", "17", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 021", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_021()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("021", "18", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 022", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_022()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("022", "19", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 023", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_023()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("023", "20", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 024", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_024()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("024", "21", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 025", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_025()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("025", "22", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 026", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_026()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("026", "23", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 040", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_040()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("040", "25", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 041", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_041()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("041", "26", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 042", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_042()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("042", "27", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 043", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_043()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("043", "28", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 044", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_044()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("044", "29", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 045", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_045()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("045", "30", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 046", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_046()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("046", "31", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 047", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_047()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("047", "32", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 048", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_048()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("048", "33", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 050", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_050()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("050", "36", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 051", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_051()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("051", "37", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 052", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_052()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("052", "38", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 053", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_053()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("053", "39", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 054", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_054()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("054", "40", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 055", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_055()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("055", "41", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 056", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_056()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("056", "42", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 057", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_057()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("057", "43", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 070", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_070()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("070", "56", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 071", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_071()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("071", "57", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 072", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_072()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("072", "58", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 073", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_073()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("073", "59", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 074", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_074()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("074", "60", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 075", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_075()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("075", "61", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 076", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_076()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("076", "62", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 077", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_077()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("077", "63", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 090", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_090()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("090", "76", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 091", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_091()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("091", "77", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 092", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_092()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("092", "78", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 093", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_093()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("093", "79", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 094", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_094()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("094", "80", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 095", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_095()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("095", "81", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 096", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_096()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("096", "82", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 097", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_097()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("097", "83", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 110", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_110()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("110", "96", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 111", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_111()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("111", "97", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 112", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_112()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("112", "98", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 113", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_113()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("113", "99", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 114", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_114()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("114", "100", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 115", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_115()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("115", "101", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 116", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_116()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("116", "102", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 117", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_117()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("117", "103", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 138", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_138()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("138", "124", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 139", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_139()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("139", "125", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 140", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_140()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("140", "126", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 141", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_141()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("141", "127", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 142", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_142()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("142", "128", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 143", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_143()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("143", "129", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 144", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_144()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("144", "130", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 145", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_145()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("145", "131", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 146", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_146()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("146", "132", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 147", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_147()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("147", "133", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 150", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_150()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("150", "136", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Uploading JSON file and Validating cards value on Closing Disclosure page, 151", SourceLine=168)]
        public virtual void UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage_151()
        {
            this.UploadingJSONFileAndValidatingCardsValueOnClosingDisclosurePage("151", "137", "ClosingDisclosure", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
